name: biscuits
channels:
  - pytorch
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anyio=4.6.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arviz=0.21.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - atk-1.0=2.36.0
  - attrs=24.3.0
  - babel=2.16.0
  - beautifulsoup4=4.12.3
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40
  - blas=1.0
  - bleach=6.2.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - cachetools=5.5.2
  - cairo=1.16.0
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - cloudpickle=3.1.1
  - comm=0.2.1
  - cons=0.4.6
  - contourpy=1.3.1
  - corner=2.2.3
  - cuda-cudart=12.4.127
  - cuda-cudart_linux-64=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.4.127
  - cuda-runtime=12.4.1
  - cuda-version=12.4
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - cython=3.0.12
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - etuples=0.3.9
  - executing=0.8.3
  - expat=2.6.4
  - ffmpeg=4.3
  - filelock=3.18.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.55.3
  - freetype=2.12.1
  - fribidi=1.0.10
  - gcc=13.3.0
  - gcc_impl_linux-64=13.3.0
  - gcc_linux-64=13.3.0
  - gdk-pixbuf=2.42.10
  - getdist=1.5.3
  - gettext=0.23.1
  - gettext-tools=0.23.1
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.15
  - graphite2=1.3.14
  - graphviz=3.0.0
  - gtk2=2.24.33
  - gts=0.7.6
  - gxx=13.3.0
  - gxx_impl_linux-64=13.3.0
  - gxx_linux-64=13.3.0
  - h11=0.14.0
  - h5netcdf=1.6.1
  - h5py=3.12.1
  - harfbuzz=4.3.0
  - hdf5=1.14.5
  - httpcore=1.0.2
  - httpx=0.27.0
  - icu=73.1
  - idna=3.7
  - imageio=2.37.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.30.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.9.25
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.3.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - kernel-headers_linux-64=3.10.0
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lame=3.100
  - lazy_loader=0.4
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libasprintf=0.23.1
  - libasprintf-devel=0.23.1
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.9.1.3
  - libcups=2.4.2
  - libcurand=10.3.5.147
  - libcurl=8.12.1
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-devel_linux-64=13.3.0
  - libgcc-ng=14.2.0
  - libgd=2.3.3
  - libgettextpo=0.23.1
  - libgettextpo-devel=0.23.1
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=14.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libltdl=2.4.3a
  - libnghttp2=1.57.0
  - libnpp=12.2.5.30
  - libnsl=2.0.1
  - libnvfatbin=12.4.127
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=4.25.3
  - librsvg=2.54.4
  - libsanitizer=13.3.0
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-devel_linux-64=13.3.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libtool=2.5.4
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxkbcommon=1.0.1
  - libxml2=2.13.5
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - logical-unification=0.4.6
  - lz4-c=1.9.4
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.6
  - mdurl=0.1.2
  - minikanren=1.0.3
  - mistune=3.1.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multipledispatch=0.6.0
  - mysql=8.4.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.4.2
  - notebook=7.3.2
  - notebook-shim=0.2.4
  - numexpr=2.10.1
  - numpy=2.2.2
  - numpy-base=2.2.2
  - ocl-icd=2.3.2
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.4.1
  - overrides=7.4.0
  - packaging=24.2
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - pango=1.50.7
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.8.0
  - pillow=11.1.0
  - pip=25.0
  - pixman=0.44.2
  - platformdirs=3.10.0
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyaml=25.1.0
  - pycparser=2.21
  - pygments=2.15.1
  - pymc=5.21.1
  - pymc-base=5.21.1
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - pysocks=1.7.1
  - pytensor=2.28.3
  - pytensor-base=2.28.3
  - python=3.12.2
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-graphviz=0.20.3
  - python-json-logger=3.2.1
  - python-tzdata=2023.3
  - python_abi=3.12
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qtbase=6.7.2
  - qtdeclarative=6.7.2
  - qtsvg=6.7.2
  - qttools=6.7.2
  - qtwebchannel=6.7.2
  - qtwebsockets=6.7.2
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.9.4
  - rpds-py=0.22.3
  - scikit-image=0.25.0
  - scikit-learn=1.6.1
  - scikit-optimize=0.10.2
  - scipy=1.15.1
  - seaborn=0.13.2
  - send2trash=1.8.2
  - setuptools=72.1.0
  - sip=6.10.0
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.2.0
  - sympy=1.13.3
  - sysroot_linux-64=2.17
  - tabulate=0.9.0
  - tbb=2021.8.0
  - terminado=0.17.1
  - threadpoolctl=3.5.0
  - tifffile=2025.2.18
  - tinycss2=1.4.0
  - tk=8.6.14
  - toolz=1.0.0
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - ultranest=4.4.0
  - unicodedata2=15.1.0
  - urllib3=2.3.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - xarray=2025.3.0
  - xarray-einstats=0.8.0
  - xcb-util-cursor=0.1.4
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
